version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: database
    env_file:
      - .env
    restart: always
    volumes:
      - ./tms.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tms-network

  java:
    build:
      context: .
      dockerfile: Dockerfile1
    container_name: backend
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mysql
    networks:
      - tms-network
      
      
  web:
    image: nginx:latest
    container_name: frontend
    ports:
      - 8000:80
    restart: always
    volumes:
      - ./web/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tms-network
  
networks:
  tms-network:
